// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHo0XOXHjVFuSOYAlVfAOkUH_HCI7d0g',
    appId: '1:218617606452:web:72f39c76f6dd72c40ab561',
    messagingSenderId: '218617606452',
    projectId: 'sistemasdigitales-5c91f',
    authDomain: 'sistemasdigitales-5c91f.firebaseapp.com',
    databaseURL: 'https://sistemasdigitales-5c91f-default-rtdb.firebaseio.com',
    storageBucket: 'sistemasdigitales-5c91f.firebasestorage.app',
    measurementId: 'G-QQ4Y13QH1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFk0esxJDLc6egFaW-SsGZ1DY_2m1QAc',
    appId: '1:218617606452:android:e6bbf168360d06040ab561',
    messagingSenderId: '218617606452',
    projectId: 'sistemasdigitales-5c91f',
    databaseURL: 'https://sistemasdigitales-5c91f-default-rtdb.firebaseio.com',
    storageBucket: 'sistemasdigitales-5c91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7tkzWXK_-UcRB9fU65oia72uePQpxJRA',
    appId: '1:218617606452:ios:3601a78f2b582eb30ab561',
    messagingSenderId: '218617606452',
    projectId: 'sistemasdigitales-5c91f',
    databaseURL: 'https://sistemasdigitales-5c91f-default-rtdb.firebaseio.com',
    storageBucket: 'sistemasdigitales-5c91f.firebasestorage.app',
    iosBundleId: 'com.example.sitemaEmbebido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7tkzWXK_-UcRB9fU65oia72uePQpxJRA',
    appId: '1:218617606452:ios:3601a78f2b582eb30ab561',
    messagingSenderId: '218617606452',
    projectId: 'sistemasdigitales-5c91f',
    databaseURL: 'https://sistemasdigitales-5c91f-default-rtdb.firebaseio.com',
    storageBucket: 'sistemasdigitales-5c91f.firebasestorage.app',
    iosBundleId: 'com.example.sitemaEmbebido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHo0XOXHjVFuSOYAlVfAOkUH_HCI7d0g',
    appId: '1:218617606452:web:3e973949dafe3ae80ab561',
    messagingSenderId: '218617606452',
    projectId: 'sistemasdigitales-5c91f',
    authDomain: 'sistemasdigitales-5c91f.firebaseapp.com',
    databaseURL: 'https://sistemasdigitales-5c91f-default-rtdb.firebaseio.com',
    storageBucket: 'sistemasdigitales-5c91f.firebasestorage.app',
    measurementId: 'G-6L78YPFGT9',
  );
}
